### PR TITLE
Remove sassc sprockets

### PR DESCRIPTION
**Pull request by langalex**
Replace tho deprecated sassc/sprockets gems and replace them with propshaft/css-/jsbundling-rails.

This requires us to add compiled JS/CSS to git (see app/assets/builds), otherwise apps using this gem would have to build it.
As a side effect, apps using Sprockets should continue to work as Sprockets can just pick up the compiled files.

## TODO

Make JS work with ESM, replace vendored JS with npm packages:
* [x] burger menu
* [x] file_upload.js
* [x] flatpickr/i18n
* [ ] redactor/i18n - not working. i18n files do not work with esm imports.
* [x] wysiwyg.js
* [x] codemirror.js

### CODE REVIEW

**Comment by avonderluft** [comment]
@langalex - note that CI tests have failed.  We will need @Judahmeek to review and approve this before merge, and he will probably ask you to squash your commits.  

cc - @justin808

**Comment by langalex** [comment]
@avonderluft sure thing. The PR is still in draft as it's not finished yet - some JS is still broken. I'll request a review when I'm there.

**Comment by langalex** [comment]
@avonderluft @Judahmeek I fixed all the JS issues I could find. Ready for review.

The only thing still broken is loading i18n strings for redactor. I think fixing this this will require an update of redactor or swapping it out for something else ([it hasn't been updated in 8 years](https://www.npmjs.com/package/redactor-wysiwyg)). This should be done in a separate PR imho.

**Comment by avonderluft** [comment]
@langalex - note that the Rails 6.1 tests failed.   Please check.

**Comment by langalex** [comment]
@avonderluft hence my other PR :)

**Comment by Judahmeek** [comment]
@langalex I merged your other PR, which means this PR needs to be rebased.

I would have rebased it myself, but you didn't enable maintainers to edit your PR.

**Comment by langalex** [comment]
> I would have rebased it myself, but you didn't enable maintainers to edit your PR.

how would I do that? add all of you as collaborators to my fork?

**Comment by langalex** [comment]
ok all rebased and tests are green.

I found a way [to not commit the compiled gems to the repo but compile them as part of the gem build process](https://github.com/shakacode/comfortable-media-surfer/pull/4/commits/02f92bd2d0180969bb9140c11eff5aabff072537).

as mentioned in the commit, the downside of this aproach is that nobody will be able to use this gem in a Gemfile via git, e.g. `gem 'comfortable_media_surfer',
    github: 'cobot/comfortable-media-surfer'`.  let me know which you prefer.

**Comment by Judahmeek** [comment]
@langalex thanks for your contribution!

re the maintainers edit feature, here's [a link to Github's documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

Basically, there should be a checkbox at the bottom of the right sidebar to enable this, whenever you're creating a PR from a fork.

**Comment by avonderluft** [comment]
@langalex - for anyone using sass stylesheets,  moving from surfer 3.0.0 to 3.1.0 has breaking changes.  Would you be willing to add something to the CHANGELOG under v3.1.0 to guide folks needing to migrate from Sprockets to Propshaft?

**Comment by langalex** [comment]
can do but I'm on vacation until Monday, so only if it can wait.

**Comment by avonderluft** [comment]
@langalex - sure that is fine.  Thank you, and much appreciated.

**Comment by avonderluft** [comment]
@langalex See https://github.com/shakacode/comfortable-media-surfer/issues/8

**Pull request merged**
